import { Race } from '@prisma/client'

export const races: Race[] = [
  {
    id: 'demi_elfe',
    name: 'Demi-elfe',
    main_race: 'Demi-elfe',
    size: 'MEDIUM',
    speed: 9,
    modifiers: ['charisma:2', 'other:1', 'other:1'],
    traits: [],
  },
  {
    id: 'demi_orc',
    name: 'Demi-orc',
    main_race: 'Demi-orc',
    size: 'MEDIUM',
    speed: 9,
    modifiers: ['strength:2', 'constitution:1'],
    traits: [],
  },
  {
    id: 'drakeide',
    name: 'Drakéide',
    main_race: 'Drakéide',
    size: 'MEDIUM',
    speed: 9,
    modifiers: ['strength:2', 'charisma:1'],
    traits: [],
  },
  {
    id: 'elfe_des_bois',
    name: 'Elfe des bois',
    main_race: 'Elfe',

    size: 'MEDIUM',
    speed: 10.5,
    modifiers: ['dexterity:2', 'wisdom:1'],
    traits: [],
  },
  {
    id: 'elfe_noir',
    name: 'Elfe noir',
    main_race: 'Elfe',

    size: 'MEDIUM',
    speed: 9,
    modifiers: ['dexterity:2', 'charisma:1'],
    traits: [],
  },
  {
    id: 'gnome_des_forets',
    name: 'Gnome des forêts',
    main_race: 'Gnome',

    size: 'SMALL',
    speed: 7.5,
    modifiers: ['dexterity:1', 'intelligence:2'],
    traits: [],
  },
  {
    id: 'gnome_des_roches',
    name: 'Gnome des roches',
    main_race: 'Gnome',
    size: 'SMALL',
    speed: 7.5,
    modifiers: ['constitution:1', 'intelligence:2'],
    traits: [],
  },
  {
    id: 'halfelin_pied_leger',
    name: 'Halfelin pied-léger',
    main_race: 'Halfelin',
    size: 'SMALL',
    speed: 7.5,
    modifiers: ['dexterity:2', 'charisma:2'],
    traits: [],
  },
  {
    id: 'halfelin_robuste',
    name: 'Halfelin robuste',
    main_race: 'Halfelin',
    size: 'SMALL',
    speed: 7.5,
    modifiers: ['dexterity:2', 'constitution:1'],
    traits: [],
  },
  {
    id: 'haut_elfe',
    name: 'Haut-elfe',
    main_race: 'Elfe',
    size: 'MEDIUM',
    speed: 9,
    modifiers: ['dexterity:2', 'intelligence:1'],
    traits: [],
  },
  {
    id: 'humain',
    name: 'Humain',
    main_race: 'Humain',
    size: 'MEDIUM',
    speed: 9,
    modifiers: [
      'strength:1',
      'dexterity:1',
      'constitution:1',
      'intelligence:1',
      'wisdom:1',
      'charisma:1',
    ],
    traits: [],
  },
  {
    id: 'nain_des_collines',
    name: 'Nain des collines',
    main_race: 'Nain',
    size: 'MEDIUM',
    speed: 7.5,
    modifiers: ['constitution:2', 'wisdom:1'],
    traits: [],
  },
  {
    id: 'nain_des_montagnes',
    name: 'Nain des montagnes',
    main_race: 'Nain',
    size: 'MEDIUM',
    speed: 7.5,
    modifiers: ['strength:2', 'constitution:2'],
    traits: [],
  },
  {
    id: 'tieffelin',
    name: 'Tieffelin',
    main_race: 'Tieffelin',
    size: 'MEDIUM',
    speed: 9,
    modifiers: ['intelligence:1', 'charisma:2'],
    traits: [],
  },
]
